# Generated by Django 6.0.5 on 2026-06-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
