# Generated by Django 6.0.5 on 2026-06-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
