# Generated by Django 6.0.5 on 2026-06-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Вариант товара', 'verbose_name_plural': 'Варианты товаров'},
        ),
        migrations.AlterModelOptions(
            name='recentlyviewed',
            options={'verbose_name': 'Просмотр', 'verbose_name_plural': 'Недавние просмотры'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
    ]
