# Generated by Django 6.0.5 on 2026-06-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Оформлен'), ('processing', 'Собирается'), ('delivery', 'В пути'), ('done', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=20),
        ),
    ]
